### ISSUE TITLE
Release tarballs do not include all contrib source

### ISSUE THREAD

**Issue by davexunit** [Librevault/librevault#63]
The source releases available here on GitHub are missing crucial source code needed to successfully build librevault because many things in `contrib` are submodules.  Full release tarballs would be a nice way to acquire the source rather than having to do an expensive, recursive git clone.

**Comment by GamePad64** [comment]
I recommend using source tarballs from https://releases.librevault.com/sources/.
These tarballs:

- Definitely complete, contain all the necessary source code (except dependencies, that are listed [here](https://github.com/Librevault/librevault/blob/master/docs/build.md#dependencies)).
- Compiled automatically from Git version tags.
- Supplemented with VERSION file, needed for building without Git, because the build system relies on `git describe` for determining the app version.
- GPG-signed by `Librevault Package Signing Key <keymaster@librevault.com>` with fingerprint `7ECA BE6D 2866 013E 2D9D  B819 F6CD DCEF 4B15 8906`
- Used for building Windows, Ubuntu, and Mac binaries.

I don't recommend using GitHub tarballs, because they are incomplete, and may cause problems during the build process.

**Comment by davexunit** [comment]
@GamePad64 thanks!  I didn't know about this because the download page on the website only mentions going to github to get the source.
