### ISSUE TITLE
[Question] Protobuf3 vs protobuf2

### ISSUE THREAD

**Issue by Strit** [Librevault/librevault#64]
Hi, I'm just wondering why protobuf version 3 is needed to build LibreVault.

Is it because version 3.0 has some feature that librevault needs?
Or could it be done with protobuf 2.6 as well?

The reason I ask, is that the version of Protobuf in Arch Linux is still only 2.6, installing 3.0 breaks many other programs.

**Comment by GamePad64** [comment]
It was originally built on protobuf 2.6, but then 3.0 was presented, and I decided to move on (ee9540ea24ebfec5ead9489b7c28208cacef9c73).

Protobuf 3.0 was recommended for use by Google since alpha releases (but not now for some reason). 
All the current features can be implemented using protobuf 2.6 (and may be partially wire-compatible with 3.0), but I don't recommend this setup.

**Comment by Strit** [comment]
Librevault does not even build with protobuf 2.6, so I'm still "forced" to wait until Arch Linux updated to protobuf v. 3.0.

Thanks for the heads up though.
