### ISSUE TITLE
Updater in Windows sometimes incorrectly detects version

### ISSUE THREAD

**Issue by mikken** [Librevault/librevault#77]
Sometimes when launching Librevault in Windows I get the message that current version is 0.1.18 and latest version is 0.1.18.10.
In fact the installed version is already 0.1.18.10.
It happens rarely, only twice so far.

**Comment by GamePad64** [comment]
Well, the updater (and all other scripts) expects the version to be in format `a.b.c`, and it does not expect `a.b.c.d` to be released in public. `a.b.c.d` format is reserved for git releases, where `d` is the commit number since the last tag (equals zero on releases).
So, this is my mistake to publish 0.1.18.10 (and 0.1.18.7) into public. I should consider incrementing `c` component instead (as it is supposed to be).
