### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by beerisgood** [librevault/librevault#85]
As users ask in the forum: https://forum.librevault.com/t/mobile-apps-for-librevault/57
it would be great if you guys can provide a Android app.

And it would be awesome if you provide that over F-Droid.

**Comment by TwanoO67** [comment]
Why F-Droid ? An official app on PlayStore would be more trustable...

But +1 for mobile apps anyway :)

**Comment by beerisgood** [comment]
F-Droid is the best option for users which like privacy and doesn't have playstore installed nor use it.
For me F-Droid is more trustable then Google playstore.

And i'm sure if you just provide the app over playstore users **will** ask you for a F-Droid version ;)

Ah and you can just provide both options. F-Droid and playstore if you like it.

**Comment by GamePad64** [comment]
I am going to provide both F-Droid and Play Store version. My build server is warmed up for building for both of them (I assume, that the same APK will not be suitable for both stores).

The synchronization daemon is built specially to be as portable as possible, so, I think, that porting it would not be a very big problem (just compile with all dependencies and start, basically).

The problem is GUI, which must be written in Java (or Qt, but it is a bad option, I think). I have no experience in Java and Android development at all, and even writing a simple GUI, that kicks HTTP requests to daemon (yes, plain-old HTTP, I am going to publish Swagger-OpenAPI specification very soon, #84) will take very much time.

**Comment by beerisgood** [comment]
Nice!
Good luck and thanks for the support!

**Comment by TwanoO67** [comment]
@GamePad64 Hi Alexander, if you have a version that could do the CLI part on Android, I would be glad to help on the GUI part

**Comment by kxra** [comment]
I'd love to see this after Issue #91 (fedora rpm packages)

**Comment by beerisgood** [comment]
How the current status for a F-Droid Android version?

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
*push*

**Comment by jeroen7s** [comment]
_push_

**Comment by DreamFlasher** [comment]
@GamePad64 what's the status/ETA?

**Comment by meeotch** [comment]
bump

**Comment by beerisgood** [comment]
*Push*

**Comment by beerisgood** [comment]
Project looks dead..

**Comment by EternityForest** [comment]
Is this still an active project?  What about just using a Web UI for the GUI? Then the Android app doesn't need any major platform specific code, it can just serve a Web UI and provide a button to open the browser.
